In [107]:
import numpy as np
import pandas as pd
import os

In [108]:
#Set the paths
registered_business_path = os.path.join('Cleaned Datasets', 'cleaned_registered_businesses.csv')
health_scores_path = os.path.join('Cleaned Datasets', 'health_scores.csv')

registered_business_df = pd.read_csv(registered_business_path)
health_scores_df = pd.read_csv(health_scores_path)

In [109]:
registered_business_df.head(10)
len(registered_business_df)

223102

In [110]:
#lower the name of the business and street address
registered_business_df['business_name'] = registered_business_df['business_name'].str.lower()
registered_business_df['street_address'] = registered_business_df['street_address'].str.lower()

#Drop any business_name or street_address that has null values
registered_business_df['street_address'].replace('', np.nan, inplace=True)
registered_business_df = registered_business_df.dropna(subset=['street_address'])

#Convert street address column to string 
registered_business_df['street_address'] = registered_business_df['street_address'].astype(str)

registered_business_df.head(1)
len(registered_business_df)

223098

In [111]:
#remove the whitespaces at the end of business and street address
registered_business_df['business_name'] = registered_business_df['business_name'].str.strip()
registered_business_df['street_address'] = registered_business_df['street_address'].str.strip()

registered_business_df.head(1)

,location_id,ownership_name,business_name,category,lic_code,street_address,State,City,zipcode,business_start_date,business_end_date,neighborhoods,business_location,supervisor_district,Lifespan,closed,age_if_opened
0,0376718-03-001,Chan Renee W,blossoming lotus acupuncture,Private Education and Health Services,NaN,2670 leavenworth st a,CA,San Francisco,94109.0,01/28/2010,NaN,North Beach,"2670 LEAVENWORTH ST\nA San Francisco, CA 94109\n",2.0,NaN,no,3106.0

In [112]:
registered_business_df.head(1)

,location_id,ownership_name,business_name,category,lic_code,street_address,State,City,zipcode,business_start_date,business_end_date,neighborhoods,business_location,supervisor_district,Lifespan,closed,age_if_opened
0,0376718-03-001,Chan Renee W,blossoming lotus acupuncture,Private Education and Health Services,NaN,2670 leavenworth st a,CA,San Francisco,94109.0,01/28/2010,NaN,North Beach,"2670 LEAVENWORTH ST\nA San Francisco, CA 94109\n",2.0,NaN,no,3106.0

In [113]:
# replace ', ", -, etc
registered_business_df['business_name'] = registered_business_df['business_name'].str.replace(r"[\"\',-.@!$%^&*]", '')

#get the first 2 words from street address
registered_business_df['formatted_address'] = registered_business_df['street_address'].str.split().str[0] + " " + registered_business_df['street_address'].str.split().str[1]
registered_business_df['formatted_name'] = registered_business_df['business_name'].str.split().str[0] + " " + registered_business_df['business_name'].str.split().str[1]

#create a unique id based off the formatted address and name
registered_business_df['uniqueid'] = registered_business_df['formatted_name'] + registered_business_df['formatted_address']


registered_business_df.head(1)

,location_id,ownership_name,business_name,category,lic_code,street_address,State,City,zipcode,business_start_date,business_end_date,neighborhoods,business_location,supervisor_district,Lifespan,closed,age_if_opened,formatted_address,formatted_name,uniqueid
0,0376718-03-001,Chan Renee W,blossoming lotus acupuncture,Private Education and Health Services,NaN,2670 leavenworth st a,CA,San Francisco,94109.0,01/28/2010,NaN,North Beach,"2670 LEAVENWORTH ST\nA San Francisco, CA 94109\n",2.0,NaN,no,3106.0,2670 leavenworth,blossoming lotus,blossoming lotus2670 leavenworth

# Clean up the health scores dataset

In [114]:
health_scores_df.head(10)

,business_id,name,address,city,state,postal_code,latitude,longitude,phone_number,score,date,type,year,month
0,19,NRGIZE LIFESTYLE CAFE,"1200 VAN NESS AVE, 3RD FLOOR",San Francisco,CA,94109,37.786848,-122.421547,14157763262,94.0,2017-12-11,routine,2017.0,12.0
1,19,NRGIZE LIFESTYLE CAFE,"1200 VAN NESS AVE, 3RD FLOOR",San Francisco,CA,94109,37.786848,-122.421547,14157763262,96.0,2018-06-07,routine,2018.0,6.0
2,19,NRGIZE LIFESTYLE CAFE,"1200 VAN NESS AVE, 3RD FLOOR",San Francisco,CA,94109,37.786848,-122.421547,14157763262,94.0,2016-05-13,routine,2016.0,5.0
3,24,OMNI S.F. HOTEL - 2ND FLOOR PANTRY,"500 CALIFORNIA ST, 2ND FLOOR",San Francisco,CA,94104,37.792888,-122.403135,14156779494,96.0,2016-03-11,routine,2016.0,3.0
4,24,OMNI S.F. HOTEL - 2ND FLOOR PANTRY,"500 CALIFORNIA ST, 2ND FLOOR",San Francisco,CA,94104,37.792888,-122.403135,14156779494,98.0,2016-10-05,routine,2016.0,10.0
5,24,OMNI S.F. HOTEL - 2ND FLOOR PANTRY,"500 CALIFORNIA ST, 2ND FLOOR",San Francisco,CA,94104,37.792888,-122.403135,14156779494,98.0,2017-11-01,routine,2017.0,11.0
6,31,NORMAN'S ICE CREAM AND FREEZES,2801 LEAVENWORTH ST,San Francisco,CA,94133,37.807155,-122.419004,NaN,98.0,2015-12-04,routine,2015.0,12.0
7,31,NORMAN'S ICE CREAM AND FREEZES,2801 LEAVENWORTH ST,San Francisco,CA,94133,37.807155,-122.419004,NaN,96.0,2018-06-15,routine,2018.0,6.0
8,45,CHARLIE'S DELI CAFE,3202 FOLSOM ST,San Francisco,CA,94110,37.747114,-122.413641,14156415051,85.0,2017-09-14,routine,2017.0,9.0
9,45,CHARLIE'S DELI CAFE,3202 FOLSOM ST,San Francisco,CA,94110,37.747114,-122.413641,14156415051,88.0,2018-05-29,routine,2018.0,5.0

In [115]:
#lower the name of the business and street address
health_scores_df['name'] = health_scores_df['name'].str.lower()
health_scores_df['address'] = health_scores_df['address'].str.lower()

#Drop any street_address that has null values
health_scores_df['address'].replace('', np.nan, inplace=True)
health_scores_df = health_scores_df.dropna(subset=['address'])

#Convert street address column to string 
health_scores_df['address'] = health_scores_df['address'].astype(str)

registered_business_df.head(1)
len(registered_business_df)

223098

In [116]:
#remove the whitespaces at the end of business and street address
health_scores_df['name'] = health_scores_df['name'].str.strip()
health_scores_df['address'] = health_scores_df['address'].str.strip()

health_scores_df.head(1)

,business_id,name,address,city,state,postal_code,latitude,longitude,phone_number,score,date,type,year,month
0,19,nrgize lifestyle cafe,"1200 van ness ave, 3rd floor",San Francisco,CA,94109,37.786848,-122.421547,14157763262,94.0,2017-12-11,routine,2017.0,12.0

In [117]:
# replace ', ", -, etc
health_scores_df['name'] = health_scores_df['name'].str.replace(r"[\"\',-.@!$%^&*]", '')

#get the first 2 words from street address
health_scores_df['formatted_address'] = health_scores_df['address'].str.split().str[0] + " " + health_scores_df['address'].str.split().str[1]
health_scores_df['formatted_name'] = health_scores_df['name'].str.split().str[0] + " " + health_scores_df['name'].str.split().str[1]

#create a unique id based off the formatted address and name
health_scores_df['uniqueid'] = health_scores_df['formatted_name'] + health_scores_df['formatted_address']

#get the columns we need
health_scores_df = health_scores_df[['business_id', 'name', 'score', 'year', 'formatted_address', 'formatted_name', 'latitude', 'longitude', 'uniqueid']]


health_scores_df.head(1)

,business_id,name,score,year,formatted_address,formatted_name,latitude,longitude,uniqueid
0,19,nrgize lifestyle cafe,94.0,2017.0,1200 van,nrgize lifestyle,37.786848,-122.421547,nrgize lifestyle1200 van

In [120]:
#Merge the registered business df with the geocodes to get unique location id
merged = registered_business_df.merge(health_scores_df, on=['uniqueid'])

In [121]:
len(merged)

24463159

In [99]:
merged.head(100)

,location_id,ownership_name,business_name,category,lic_code,street_address,State,City,zipcode,business_start_date,...,closed,age_if_opened,formatted_address,formatted_name,business_id,name,score,year,latitude,longitude
0,1173752-12-171,Yo-Kai Express Inc.,yokai express inc,Food Services,NaN,135 4th st ste 4000,CA,San Francisco,94103.0,12/28/2017,...,no,215.0,135 4th,yokai express,94310,yokai express,100.0,2018.0,NaN,NaN
1,1173814-12-171,"Gan Xiang Yu, Llc",sizzling pot king,Food Services,"Restaurant 1,000 - 2,000 Sqft",139 8th st,CA,San Francisco,94103.0,12/28/2017,...,no,215.0,139 8th,sizzling pot,94408,sizzling pot king,86.0,2018.0,NaN,NaN
2,1173814-12-171,"Gan Xiang Yu, Llc",sizzling pot king,Food Services,"Restaurant 1,000 - 2,000 Sqft",139 8th st,CA,San Francisco,94103.0,12/28/2017,...,no,215.0,139 8th,sizzling pot,94408,sizzling pot king,80.0,2018.0,NaN,NaN
3,0015092-01-001,Jug Shop Inc,jug shop inc,Retail Trade,Multiple,1590 pacific ave,CA,San Francisco,94108.0,10/01/1968,...,no,18200.0,1590 pacific,jug shop,23704,jug shop inc,92.0,2017.0,37.79511,-122.421411
4,0015092-01-001,Jug Shop Inc,jug shop inc,Retail Trade,Multiple,1590 pacific ave,CA,San Francisco,94108.0,10/01/1968,...,no,18200.0,1590 pacific,jug shop,23704,jug shop inc,90.0,2016.0,37.79511,-122.421411
5,0015092-01-001,Jug Shop Inc,jug shop inc,Retail Trade,Multiple,1590 pacific ave,CA,San Francisco,94108.0,10/01/1968,...,no,18200.0,1590 pacific,jug shop,23704,jug shop inc,96.0,2016.0,37.79511,-122.421411
6,1037510-08-151,Sweetch Inc,jug shop,"Professional, Scientific, and Technical Services",NaN,1590 pacific ave,CA,San Francisco,94109.0,01/06/2015,...,yes,NaN,1590 pacific,jug shop,23704,jug shop inc,92.0,2017.0,37.79511,-122.421411
7,1037510-08-151,Sweetch Inc,jug shop,"Professional, Scientific, and Technical Services",NaN,1590 pacific ave,CA,San Francisco,94109.0,01/06/2015,...,yes,NaN,1590 pacific,jug shop,23704,jug shop inc,90.0,2016.0,37.79511,-122.421411
8,1037510-08-151,Sweetch Inc,jug shop,"Professional, Scientific, and Technical Services",NaN,1590 pacific ave,CA,San Francisco,94109.0,01/06/2015,...,yes,NaN,1590 pacific,jug shop,23704,jug shop inc,96.0,2016.0,37.79511,-122.421411
9,1122826-10-161,"Volans-I, Inc.",runway,NaN,NaN,1355 market st,CA,San Francisco,94103.0,12/31/2015,...,no,943.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
10,1122826-10-161,"Volans-I, Inc.",runway,NaN,NaN,1355 market st,CA,San Francisco,94103.0,12/31/2015,...,no,943.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
11,1122826-10-161,"Volans-I, Inc.",runway,NaN,NaN,1355 market st,CA,San Francisco,94103.0,12/31/2015,...,no,943.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
12,1122826-10-161,"Volans-I, Inc.",runway,NaN,NaN,1355 market st,CA,San Francisco,94103.0,12/31/2015,...,no,943.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
13,1074581-06-161,Essociate Inc,huntingmooncom,"Professional, Scientific, and Technical Services",NaN,1355 market st 4,CA,San Francisco,94103.0,01/01/2001,...,no,6420.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
14,1074581-06-161,Essociate Inc,huntingmooncom,"Professional, Scientific, and Technical Services",NaN,1355 market st 4,CA,San Francisco,94103.0,01/01/2001,...,no,6420.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
15,1074581-06-161,Essociate Inc,huntingmooncom,"Professional, Scientific, and Technical Services",NaN,1355 market st 4,CA,San Francisco,94103.0,01/01/2001,...,no,6420.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
16,1074581-06-161,Essociate Inc,huntingmooncom,"Professional, Scientific, and Technical Services",NaN,1355 market st 4,CA,San Francisco,94103.0,01/01/2001,...,no,6420.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
17,1177449-01-181,"Myways, Inc.",circleof,"Professional, Scientific, and Technical Services",NaN,1355 market st #488,CA,San Francisco,94103.0,12/01/2017,...,no,242.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
18,1177449-01-181,"Myways, Inc.",circleof,"Professional, Scientific, and Technical Services",NaN,1355 market st #488,CA,San Francisco,94103.0,12/01/2017,...,no,242.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
19,1177449-01-181,"Myways, Inc.",circleof,"Professional, Scientific, and Technical Services",NaN,1355 market st #488,CA,San Francisco,94103.0,12/01/2017,...,no,242.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
20,1177449-01-181,"Myways, Inc.",circleof,"Professional, Scientific, and Technical Services",NaN,1355 market st #488,CA,San Francisco,94103.0,12/01/2017,...,no,242.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
21,1180073-02-181,"Retalent, Inc.",retalent,"Professional, Scientific, and Technical Services",NaN,1355 market st bldg 488,CA,San Francisco,94103.0,10/11/2017,...,no,293.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
22,1180073-02-181,"Retalent, Inc.",retalent,"Professional, Scientific, and Technical Services",NaN,1355 market st bldg 488,CA,San Francisco,94103.0,10/11/2017,...,no,293.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
23,1180073-02-181,"Retalent, Inc.",retalent,"Professional, Scientific, and Technical Services",NaN,1355 market st bldg 488,CA,San Francisco,94103.0,10/11/2017,...,no,293.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
24,1180073-02-181,"Retalent, Inc.",retalent,"Professional, Scientific, and Technical Services",NaN,1355 market st bldg 488,CA,San Francisco,94103.0,10/11/2017,...,no,293.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
25,1188345-05-181,Zensoft.io,zensoftio,"Professional, Scientific, and Technical Services",NaN,1355 market st ste 488,CA,San Francisco,93104.0,07/01/2016,...,no,760.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
26,1188345-05-181,Zensoft.io,zensoftio,"Professional, Scientific, and Technical Services",NaN,1355 market st ste 488,CA,San Francisco,93104.0,07/01/2016,...,no,760.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
27,1188345-05-181,Zensoft.io,zensoftio,"Professional, Scientific, and Technical Services",NaN,1355 market st ste 488,CA,San Francisco,93104.0,07/01/2016,...,no,760.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
28,1188345-05-181,Zensoft.io,zensoftio,"Professional, Scientific, and Technical Services",NaN,1355 market st ste 488,CA,San Francisco,93104.0,07/01/2016,...,no,760.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
29,1021649-03-151,"Acompli, Inc.",acompli,NaN,NaN,1355 market st 3rd flr,CA,San Francisco,94103.0,02/01/2014,...,yes,NaN,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,0481918-01-001,Pro Populi Inc,people+,"Professional, Scientific, and Technical Services",NaN,1355 market st,CA,San Francisco,94103.0,07/29/2013,...,no,1828.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
71,0481918-01-001,Pro Populi Inc,people+,"Professional, Scientific, and Technical Services",NaN,1355 market st,CA,San Francisco,94103.0,07/29/2013,...,no,1828.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
72,0481918-01-001,Pro Populi Inc,people+,"Professional, Scientific, and Technical Services",NaN,1355 market st,CA,San Francisco,94103.0,07/29/2013,...,no,1828.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
73,0487439-01-001,Credible Labs Inc,credible,Financial Services,NaN,1355 market st 488,CA,San Francisco,94103.0,03/01/2013,...,no,1978.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
74,0487439-01-001,Credible Labs Inc,credible,Financial Services,NaN,1355 market st 488,CA,San Francisco,94103.0,03/01/2013,...,no,1978.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
75,0487439-01-001,Credible Labs Inc,credible,Financial Services,NaN,1355 market st 488,CA,San Francisco,94103.0,03/01/2013,...,no,1978.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
76,0487439-01-001,Credible Labs Inc,credible,Financial Services,NaN,1355 market st 488,CA,San Francisco,94103.0,03/01/2013,...,no,1978.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
77,0489262-01-001,Cnry Inc,birdi,Manufacturing,NaN,1355 market st 488,CA,San Francisco,94103.0,04/04/2014,...,no,1579.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
78,0489262-01-001,Cnry Inc,birdi,Manufacturing,NaN,1355 market st 488,CA,San Francisco,94103.0,04/04/2014,...,no,1579.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
79,0489262-01-001,Cnry Inc,birdi,Manufacturing,NaN,1355 market st 488,CA,San Francisco,94103.0,04/04/2014,...,no,1579.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
80,0489262-01-001,Cnry Inc,birdi,Manufacturing,NaN,1355 market st 488,CA,San Francisco,94103.0,04/04/2014,...,no,1579.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
81,0489329-01-001,Autotrophic Labs Inc,hiplead,Information,NaN,1355 market st #488 488,CA,San+francisco,94103.0,05/05/2014,...,no,1548.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
82,0489329-01-001,Autotrophic Labs Inc,hiplead,Information,NaN,1355 market st #488 488,CA,San+francisco,94103.0,05/05/2014,...,no,1548.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
83,0489329-01-001,Autotrophic Labs Inc,hiplead,Information,NaN,1355 market st #488 488,CA,San+francisco,94103.0,05/05/2014,...,no,1548.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
84,0489329-01-001,Autotrophic Labs Inc,hiplead,Information,NaN,1355 market st #488 488,CA,San+francisco,94103.0,05/05/2014,...,no,1548.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
85,1009205-10-141,Reviver Mx Inc,reviver,NaN,NaN,1355 market st #488,CA,San Francisco,94103.0,10/09/2014,...,yes,NaN,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
86,1009205-10-141,Reviver Mx Inc,reviver,NaN,NaN,1355 market st #488,CA,San Francisco,94103.0,10/09/2014,...,yes,NaN,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
87,1009205-10-141,Reviver Mx Inc,reviver,NaN,NaN,1355 market st #488,CA,San Francisco,94103.0,10/09/2014,...,yes,NaN,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
88,1009205-10-141,Reviver Mx Inc,reviver,NaN,NaN,1355 market st #488,CA,San Francisco,94103.0,10/09/2014,...,yes,NaN,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
89,1015209-12-141,Cbconcept Corporation,cbconcept,Wholesale Trade,NaN,1355 market st 4th,CA,San Francisco,94103.0,05/01/2009,...,yes,NaN,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
90,1015209-12-141,Cbconcept Corporation,cbconcept,Wholesale Trade,NaN,1355 market st 4th,CA,San Francisco,94103.0,05/01/2009,...,yes,NaN,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
91,1015209-12-141,Cbconcept Corporation,cbconcept,Wholesale Trade,NaN,1355 market st 4th,CA,San Francisco,94103.0,05/01/2009,...,yes,NaN,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
92,1015209-12-141,Cbconcept Corporation,cbconcept,Wholesale Trade,NaN,1355 market st 4th,CA,San Francisco,94103.0,05/01/2009,...,yes,NaN,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
93,1008308-09-141,Azalina's Restaurant Llc,azalinas,Food Services,Take-Out Establishment,1355 market st,CA,San Francisco,94127.0,09/29/2014,...,no,1401.0,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
94,1008308-09-141,Azalina's Restaurant Llc,azalinas,Food Services,Take-Out Establishment,1355 market st,CA,San Francisco,94127.0,09/29/2014,...,no,1401.0,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
95,1008308-09-141,Azalina's Restaurant Llc,azalinas,Food Services,Take-Out Establishment,1355 market st,CA,San Francisco,94127.0,09/29/2014,...,no,1401.0,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN
96,1008308-09-141,Azalina's Restaurant Llc,azalinas,Food Services,Take-Out Establishment,1355 market st,CA,San Francisco,94127.0,09/29/2014,...,no,1401.0,1355 market,NaN,80659,azalinas,92.0,2017.0,NaN,NaN
97,1031582-06-151,Invine Inc,invine,Information,NaN,1355 market st #488,CA,San Francisco,94103.0,06/15/2015,...,yes,NaN,1355 market,NaN,80659,azalinas,91.0,2018.0,NaN,NaN
98,1031582-06-151,Invine Inc,invine,Information,NaN,1355 market st #488,CA,San Francisco,94103.0,06/15/2015,...,yes,NaN,1355 market,NaN,80659,azalinas,83.0,2016.0,NaN,NaN
99,1031582-06-151,Invine Inc,invine,Information,NaN,1355 market st #488,CA,San Francisco,94103.0,06/15/2015,...,yes,NaN,1355 market,NaN,80659,azalinas,94.0,2017.0,NaN,NaN

In [96]:
path = os.path.join('Cleaned Datasets', 'final-merged.csv')
merged.to_csv(path, index=False)